/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.io.File;
import java.io.IOException;
import javax.swing.JOptionPane;
import metodos_uml.uml_metodos;

/**
 *
 * @author USER
 */
public class panel_invitado extends javax.swing.JFrame {

    /**
     * Creates new form panel_invitado
     */
    public panel_invitado() {
        initComponents();
        this.setTitle("MODO INVITADO");
        this.setLocationRelativeTo(null);  // Centrar la ventana
        this.setResizable(false);  // Evitar maximización
    }
    private File imagenGenerada;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Jimagen = new javax.swing.JLabel();
        btnlimpiar = new javax.swing.JButton();
        panelCodigo = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        item_salir = new javax.swing.JMenu();
        ite_subirArch = new javax.swing.JMenuItem();
        item_eleminar = new javax.swing.JMenuItem();
        itm_cerrar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setText("GENERAR CODIGO");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 380, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Diagrama visor");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        Jimagen.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        getContentPane().add(Jimagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 430, 320));

        btnlimpiar.setText("LIMPIAR");
        btnlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnlimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("\n\n\n\n\n\n\n\n\n\n");
        jTextArea1.setMargin(new java.awt.Insets(28, 28, 200, 6));
        jScrollPane2.setViewportView(jTextArea1);

        panelCodigo.add(jScrollPane2);

        getContentPane().add(panelCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 260, 310));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/fondo4.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 440));

        item_salir.setText("ARCHIVO");

        ite_subirArch.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.SHIFT_DOWN_MASK | java.awt.event.InputEvent.CTRL_DOWN_MASK));
        ite_subirArch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/itmesubir.png"))); // NOI18N
        ite_subirArch.setText("SUBIR ARCHIVO");
        ite_subirArch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ite_subirArchActionPerformed(evt);
            }
        });
        item_salir.add(ite_subirArch);

        item_eleminar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_DELETE, java.awt.event.InputEvent.SHIFT_DOWN_MASK));
        item_eleminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Iitemeliminar.png"))); // NOI18N
        item_eleminar.setText("ELIMINAR");
        item_eleminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_eleminarActionPerformed(evt);
            }
        });
        item_salir.add(item_eleminar);

        itm_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/itemcrerrar.png"))); // NOI18N
        itm_cerrar.setText("CERRAR");
        itm_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itm_cerrarActionPerformed(evt);
            }
        });
        item_salir.add(itm_cerrar);

        jMenuBar1.add(item_salir);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ite_subirArchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ite_subirArchActionPerformed
        // Abrimos el archivo UML que subió el usuario
        File archivoUML = uml_metodos.cargarArchivoUML(this);

        if (archivoUML != null) {
            try {
                // Convertimos el archivo a imagen pa ver una vista previa
                imagenGenerada = uml_metodos.convertirUMLAImagen(archivoUML); 

                // Si la imagen se generó bien, la mostramos
                if (imagenGenerada != null) {
                    int opcion = uml_metodos.mostrarVistaPrevia(archivoUML, imagenGenerada, this);

                    // Si el usuario dice que sí, mostramos la imagen en el JLabel
                    if (opcion == JOptionPane.YES_OPTION) {
                        uml_metodos.mostrarImagen(imagenGenerada, Jimagen); // Mostramos la imagen en el JLabel
                    } else {
                        // Si dijo que no, pues no hacemos nada
                        JOptionPane.showMessageDialog(this, "La imagen no fue seleccionada para mostrar.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                    }
                } else {
                    // Error si no se pudo generar la imagen
                    JOptionPane.showMessageDialog(this, "No se pudo generar la imagen del diagrama.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (IOException e) {
                // Error si algo falló al convertir el archivo a imagen
                JOptionPane.showMessageDialog(this, "Error al convertir el archivo UML a imagen: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_ite_subirArchActionPerformed

    private void itm_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itm_cerrarActionPerformed
        // TODO add your handling code here:
        inicio_login n = new inicio_login();
        n.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_itm_cerrarActionPerformed

    private void btnlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarActionPerformed
        Jimagen.setIcon(null); 
        Jimagen.revalidate();  
        Jimagen.repaint();
    }//GEN-LAST:event_btnlimpiarActionPerformed

    private void item_eleminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_eleminarActionPerformed
        // Seleccionar el archivo a eliminar 
        File archivoParaEliminar = uml_metodos.seleccionarArchivoParaEliminar(this);
        // Eliminar el archivo seleccionado
        uml_metodos.eliminarArchivo(this, archivoParaEliminar, Jimagen);
    }//GEN-LAST:event_item_eleminarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jTextArea1.setText("Este es un ejemplo que se ve ya que no se genera codigo en este sprint");
            
        // Redibujar el panel para que refleje los cambios
        panelCodigo.revalidate();
        panelCodigo.repaint();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(panel_invitado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(panel_invitado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(panel_invitado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(panel_invitado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new panel_invitado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Jimagen;
    private javax.swing.JButton btnlimpiar;
    private javax.swing.JMenuItem ite_subirArch;
    private javax.swing.JMenuItem item_eleminar;
    private javax.swing.JMenu item_salir;
    private javax.swing.JMenuItem itm_cerrar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel panelCodigo;
    // End of variables declaration//GEN-END:variables
}
